version: '3.8'

services:
  api:
    build: .
    container_name: nest-api
    ports:
      - '3000:3000'
    depends_on:
      - postgres
      - redis
    env_file:
      - .env
    volumes:
      - .:/app
      - /app/node_modules
    command: npm run start:dev

  postgres:
    image: postgres:15
    container_name: postgres-db
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: abdulloh798
      POSTGRES_DB: lms_db
    volumes:
      - pgdata:/var/lib/postgresql/data

  redis:
    image: redis:7
    container_name: redis-cache
    ports:
      - '6379:6379'

volumes:
  pgdata:
